### ISSUE TITLE
STDOUT sink only logs to stderr

### ISSUE THREAD

**Issue by nugend** [seatgeek/nomad-firehose#1]
Could it actually just write to stdout? That would make it easy to use to pipeline the json objects through scripts such as jq (or other stuff).

**Comment by jippi** [comment]
I guess, we can change https://github.com/seatgeek/nomad-firehose/blob/master/sink/stdout.go#L54 to just be `fmt.Println()` instead :)

**Comment by jippi** [comment]
Done :D

**Comment by jippi** [comment]
Docker will rebuild automatically

**Comment by nugend** [comment]
Lol. Fastest turnaround on an issue I've ever seen. Thanks man.

**Comment by jippi** [comment]
kinda clever to pipeline to `jq`, didn't think about that

**Comment by jippi** [comment]
binary release should be up in https://github.com/seatgeek/nomad-firehose/releases/tag/v0.1.1 within a few minutes when travis finishes up
