### ISSUE TITLE
Should it pass to amqp message about running state of a job twice identical?

### ISSUE THREAD

**Issue by mikefaraponov** [seatgeek/nomad-firehose#16]
My current configuration is Nomad in dev mode. Consul in dev mode latest versions.
AMQP receives first two messages identical when job is submitted about running state.
Single nomad-firehose instance.

**Comment by mikefaraponov** [comment]
I see that in docs described some behavior about duplicated events. This is it?

**Comment by mikefaraponov** [comment]
Do you think about contributing to nomad source to integrate notifications engine into nomad core?

**Comment by jippi** [comment]
I've fixed a bunch of bugs in master/latest/1.1.0 - take them for a spin and reopen if you still see issues
