### ISSUE TITLE
[feature request] additional sink

### ISSUE THREAD

**Issue by MorphBonehunter** [seatgeek/nomad-firehose#2]
Over the weekend i experiment a little bit with nomad-firehose.
My idea was to use this tool to notify me, if an job fails.
As i do not have Kinesis or an MQ, i wrote a little python script which collects the stdout sink, analyse it and do actions based on the output.
At the moment this isn't realy practicable if it is used as an daemon (in my case systemd as init) because my unit file contains:
`ExecStart=/usr/bin/bash -c "/usr/bin/nomad-firehose allocations | /usr/bin/nomad-firehose-milter"`

So maybe a sink could be implemented which starts a defined program and pipes the stdout to this tool. Maybe something like that:
```
SINK=filter
SINK_PROG= /usr/bin/nomad-firehose-milter
```

**Comment by josegonzalez** [comment]
Why not write the data out to stdout, collect that to a file, and have your program follow that file instead?

**Comment by MorphBonehunter** [comment]
@josegonzalez this would require also an `bash -c` as this means also an output redirection as long as nomad-firehose doesn't integrate an "logfile sink".
I would prefer the all-in-one approach if firehose could handover his data to another "tool".

**Comment by josegonzalez** [comment]
My gut says you can use your process supervisor to redirect the output of nomad-firehose to a file and then tail the log output of that file with your tool.

I'll leave whether integrating piping directly to a tool is something we'd implement to @jippi since this is his baby :)

**Comment by jippi** [comment]
stdout should be able to do this - if not - PR is welcome
