### ISSUE TITLE
FR: Allow option to connect to Kafka sink over TLS

### ISSUE THREAD

**Issue by ckong1991** [seatgeek/nomad-firehose#25]
The idea is to modify the sarama config to pass in the TLS struct
https://godoc.org/github.com/Shopify/sarama#Config

happy to open a PR to address this

**Comment by jippi** [comment]
PR welcome :)

**Comment by ckong1991** [comment]
@jippi can you give me access to the repo so I can submit my PR?

**Comment by josegonzalez** [comment]
@ckong1991 you can submit a pull request from a repository fork. Here are [some docs](https://help.github.com/articles/fork-a-repo/) from github.

**Comment by ckong1991** [comment]
@jippi @josegonzalez opened a PR

**Comment by jippi** [comment]
Fixed in #26

**Comment by jippi** [comment]
Thank you @ckong1991 !

**Comment by ckong1991** [comment]
awesome, any chance you'll create a new release @jippi ?

**Comment by jippi** [comment]
https://github.com/seatgeek/nomad-firehose/releases/tag/v1.3.0 done - should be complete in ~10min

**Comment by ckong1991** [comment]
thanks!
