### ISSUE TITLE
Stream partition keying

### ISSUE THREAD

**Issue by wyattanderson** [seatgeek/nomad-firehose#33]
We have such high batch throughput that we need to use multiple partitions (and thus multiple consumers) on the Kafka topic we use for processing allocation events. We'd like to be able to maintain ordering for allocation and job updates in this case, and doing so requires setting a partition key when we publish messages to that topic.

I think it makes sense to use the allocation ID (or job ID, or evaluation ID, or node ID, etc.) as the partition key so that any messages for a given allocation are received in order when processing allocations, any messages for a given job are processed in order, etc. I was thinking of modifying the `Sink.Put` to take a `key []byte` (or something) in addition to the `data []byte`.

I noticed that the Kinesis sink is configured to take a _static_ partition key, though, and so I don't know if my proposal will hurt that use case. Maybe it makes sense to use the static partition key—if configured—and use the computed partition key otherwise.

Thoughts? I can send a PR if it would help illustrate things.

**Comment by josegonzalez** [comment]
Seems legit. We'd like to keep the current setup as default if possible, but all pull requests are welcome :)

**Comment by ckong1991** [comment]
I opened https://github.com/seatgeek/nomad-firehose/pull/36 - let me know what you think @josegonzalez

**Comment by ckong1991** [comment]
@jippi any thoughts?
