### ISSUE TITLE
Plan for the next release?

### ISSUE THREAD

**Issue by zhiguangwang** [seatgeek/nomad-firehose#42]
The `http` sink implemented in #27 has not been released yet.

Looking forward to the next release of nomad-firehose!

**Comment by jippi** [comment]
Hi ! 

This is now done - https://github.com/seatgeek/nomad-firehose/releases/tag/v1.4.0

Sorry about that

**Comment by zhiguangwang** [comment]
Thank you!

**Comment by jippi** [comment]
hmm, looks like it didn't push it :(

**Comment by burdandrei** [comment]
yes, and then DockerHub leak disconnected the accounts. `v1.4.0` pushed, `latest` updated

**Comment by zhiguangwang** [comment]
Got it, thanks :)
